### ISSUE TITLE
JS asset doesn't work in IE

### ISSUE THREAD

**Issue by zipper** [peckadesign/AsyncControl#8]
Provided JS nette extension does not work in IE because of `new CustomEvent()` is used. Since there are no data passed into that event, I suppose it would be sufficient to [use `Event` constructor instead](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events), which would be compatible at least with IE11.

**Comment by zipper** [comment]
Prepared in PR #9.

**Comment by vitkutny** [comment]
Merged in https://github.com/peckadesign/AsyncControl/commit/57f0e9cbe2d19f0405c495047dfa26238060b92c.

**Comment by zipper** [comment]
Turns out, that IE doesn't support `Event()` constructor either. Please see PR #10.

**Comment by vitkutny** [comment]
Merged. Thanks.
